import { calculateCounts, calculateGauge } from "./calculation-core.js";
import { convertUnitValue, formatDate, formatExact, parseLocalizedDecimal } from "./ui-utils.js";

const STORAGE_KEY = "marina.history.v1";
const state = { mode: "gauge", detailMode: "simple", language: document.documentElement.lang || "ru", history: loadHistory(), lastResult: null, lastInput: null };
const $ = (selector) => document.querySelector(selector);

const copy = {
  ru: {
    eyebrow: "Точный расчёт для спокойного вязания", title: "Плотность, петли<br />и ряды — без догадок.", intro: "Введите данные образца или плотность и получите проверяемый размер готового полотна.", modeGauge: "Рассчитать плотность", modeCounts: "Рассчитать петли", saved: "Сохранённые расчёты", historyTitle: "История", clear: "Очистить", exportHistory: "Скачать историю", printResult: "Печать / PDF", exported: "История скачана", offline: "Работает офлайн после первого запуска", calculate: "Рассчитать", sample: "Данные образца", stitches: "Петель", rows: "Рядов", width: "Ширина образца", height: "Высота образца", targetWidth: "Ширина полотна", targetHeight: "Высота полотна", density: "Плотность", stitchDensity: "Петель на единицу", rowDensity: "Рядов на единицу", unit: "Единица измерения", cm: "см", inch: "дюйм", flat: "Плоское вязание", round: "По кругу", construction: "Способ вязания", rules: "Правила округления", stitchRule: "Петли", rowRule: "Ряды", down: "Вниз", up: "Вверх", nearest: "Ближайшее", multiple: "Раппорт", offset: "Смещение", edge: "Кромочные", optional: "необязательно", projectName: "Название проекта", result: "Результат", raw: "Исходное значение", rounded: "После округления", final: "Итого", actual: "Фактический размер", delta: "Отклонение", savedAt: "Сохранено", emptyHistory: "Здесь появятся ваши расчёты.", copied: "Результат скопирован", shareFailed: "Скопируйте результат вручную", invalid: "Проверьте выделенные поля", share: "Копировать карточку", noResult: "Заполните поля, чтобы увидеть результат", gaugeResult: "Ваша плотность", countsResult: "Расчёт полотна", edgeRound: "В круговом вязании кромочные не используются", clearConfirm: "Удалить всю историю?", guideTitle: "Три спокойных шага", guideOne: "Введите данные образца", guideTwo: "Выберите единицы и правила", guideThree: "Получите число и фактический размер", exactNote: "Единицы пересчитываются точно: 1 дюйм = 2,54 см.", measureGuideTitle: "Как измерить образец", measureOne: "Свяжите образец с запасом по краям", measureTwo: "Постирайте и высушите его как изделие", measureThree: "Измерьте середину, не край", measureNote: "Плотность зависит от стирки, поэтому считайте по фактическому образцу.", summaryGauge: "В образце", summaryCounts: "Для готового полотна", densityWarning: "Проверьте измерения: такая плотность выглядит необычно.", simpleMode: "Простой", advancedMode: "Расширенный", advancedHint: "Раппорт, кромочные и правила округления", errorNumber: "введите число", errorInteger: "введите целое число", errorPositive: "укажите значение больше нуля", errorCount: "укажите положительное количество", errorUnit: "выберите единицу измерения", errorConstruction: "выберите способ вязания", errorRounding: "выберите правило округления", errorRepeat: "укажите положительный раппорт", errorOffset: "смещение должно быть меньше раппорта", errorEdge: "проверьте число кромочных петель", errorZero: "результат должен быть больше нуля"
  },
  en: {
    eyebrow: "Precise calculations for mindful knitting", title: "Gauge, stitches<br />and rows — no guesswork.", intro: "Enter your swatch data or gauge to get a verifiable finished fabric size.", modeGauge: "Calculate gauge", modeCounts: "Calculate counts", saved: "Saved calculations", historyTitle: "History", clear: "Clear", exportHistory: "Download history", printResult: "Print / PDF", exported: "History downloaded", offline: "Works offline after the first launch", calculate: "Calculate", sample: "Swatch data", stitches: "Stitches", rows: "Rows", width: "Swatch width", height: "Swatch height", targetWidth: "Fabric width", targetHeight: "Fabric height", density: "Gauge", stitchDensity: "Stitches per unit", rowDensity: "Rows per unit", unit: "Unit", cm: "cm", inch: "in", flat: "Flat knitting", round: "In the round", construction: "Construction", rules: "Rounding rules", stitchRule: "Stitches", rowRule: "Rows", down: "Down", up: "Up", nearest: "Nearest", multiple: "Repeat", offset: "Offset", edge: "Edge stitches", optional: "optional", projectName: "Project name", result: "Result", raw: "Raw value", rounded: "After rounding", final: "Total", actual: "Actual size", delta: "Difference", savedAt: "Saved", emptyHistory: "Your calculations will appear here.", copied: "Result copied", shareFailed: "Copy the result manually", invalid: "Check the highlighted fields", share: "Copy card", noResult: "Fill in the fields to see your result", gaugeResult: "Your gauge", countsResult: "Fabric calculation", edgeRound: "Edge stitches are not used in the round", clearConfirm: "Delete all history?", guideTitle: "Three calm steps", guideOne: "Enter your swatch data", guideTwo: "Choose units and rules", guideThree: "Get the count and actual size", exactNote: "Units convert exactly: 1 inch = 2.54 cm.", measureGuideTitle: "How to measure a swatch", measureOne: "Knit a swatch with extra room around the edges", measureTwo: "Wash and dry it as you would the finished item", measureThree: "Measure the middle, not the edge", measureNote: "Gauge changes after washing, so use the real finished swatch.", summaryGauge: "In your swatch", summaryCounts: "For the finished fabric", densityWarning: "Check your measurements: this gauge looks unusual.", simpleMode: "Simple", advancedMode: "Advanced", advancedHint: "Repeat, edge stitches and rounding rules", errorNumber: "enter a number", errorInteger: "enter a whole number", errorPositive: "enter a value above zero", errorCount: "enter a positive count", errorUnit: "choose a unit", errorConstruction: "choose a construction", errorRounding: "choose a rounding rule", errorRepeat: "enter a positive repeat", errorOffset: "offset must be smaller than repeat", errorEdge: "check the number of edge stitches", errorZero: "the result must be above zero"
  }
};

function t(key) { return copy[state.language][key] || key; }
function loadHistory() { try { return JSON.parse(localStorage.getItem(STORAGE_KEY) || "[]"); } catch { return []; } }
function saveHistory(entry) { state.history = [entry, ...state.history].slice(0, 8); localStorage.setItem(STORAGE_KEY, JSON.stringify(state.history)); renderHistory(); }
function errorText(error) { const names = { invalid_number: t("errorNumber"), invalid_integer: t("errorInteger"), non_positive_measurement: t("errorPositive"), non_positive_count: t("errorCount"), non_positive_density: t("errorPositive"), invalid_unit: t("errorUnit"), invalid_construction: t("errorConstruction"), invalid_rounding: t("errorRounding"), invalid_rational: t("errorNumber"), non_positive_multiple: t("errorRepeat"), invalid_offset: t("errorOffset"), edge_stitches_in_round: t("edgeRound"), negative_raw_body: t("errorEdge"), zero_result_count: t("errorZero") }; const fields = { stitches: t("stitches"), rows: t("rows"), width: t("width"), height: t("height"), stitchDensity: t("stitchDensity"), rowDensity: t("rowDensity"), targetWidth: t("targetWidth"), targetHeight: t("targetHeight"), unit: t("unit"), construction: t("construction"), "stitchRule.multiple": `${t("stitchRule")} — ${t("multiple")}`, "stitchRule.offset": `${t("stitchRule")} — ${t("offset")}`, "stitchRule.edgeStitches": `${t("stitchRule")} — ${t("edge")}`, "rowRule.multiple": `${t("rowRule")} — ${t("multiple")}`, "rowRule.offset": `${t("rowRule")} — ${t("offset")}`, "stitches.final": `${t("stitchRule")} — ${t("final")}`, "rows.final": `${t("rowRule")} — ${t("final")}` }; return `${fields[error.field] || error.field}: ${names[error.code] || error.code}`; }

function field(id, label, type = "text", value = "") { return `<label class="field"><span>${label}</span><input id="${id}" name="${id}" type="${type}" inputmode="decimal" value="${value}" autocomplete="off" /></label>`; }
function textField(id, label) { return `<label class="field text-field"><span>${label}</span><input id="${id}" name="${id}" type="text" value="" autocomplete="off" /></label>`; }
function unitSelect() { return `<label class="field compact"><span>${t("unit")}</span><select id="unit"><option value="cm">${t("cm")}</option><option value="in">${t("inch")}</option></select></label>`; }
function ruleSelect(id) { return `<select id="${id}"><option value="nearest">${t("nearest")}</option><option value="down">${t("down")}</option><option value="up">${t("up")}</option></select>`; }
function ruleBlock(prefix, title, edges = false) { return `<div class="rule-row"><div><strong>${title}</strong><small>${t("rules")}</small></div>${ruleSelect(`${prefix}Rounding`)}${field(`${prefix}Multiple`, t("multiple"), "text", "1")}${field(`${prefix}Offset`, t("offset"), "text", "0")}${edges ? field("edgeStitches", t("edge"), "text", "0") : ""}</div>`; }

function render() { $("#calculator").innerHTML = `<div class="workspace-grid"><div class="calculator-column">${state.mode === "gauge" ? gaugeForm() : countsForm()}</div>${guide()}</div>`; bindForm(); renderHistory(); updateLanguage(); }
function guide() { const measurement = state.mode === "gauge"; return `<aside class="guide-panel" aria-label="${t(measurement ? "measureGuideTitle" : "guideTitle")}"><p class="eyebrow">Marina</p><h2>${t(measurement ? "measureGuideTitle" : "guideTitle")}</h2><ol><li>${t(measurement ? "measureOne" : "guideOne")}</li><li>${t(measurement ? "measureTwo" : "guideTwo")}</li><li>${t(measurement ? "measureThree" : "guideThree")}</li></ol><p class="guide-note">${t(measurement ? "measureNote" : "exactNote")}</p></aside>`; }
function gaugeForm() { return `<form id="gauge-form" class="calculator-form"><div class="form-heading"><span class="step">01</span><div><p class="eyebrow">${t("sample")}</p><h2>${t("sample")}</h2></div></div><div class="form-grid">${field("stitches", t("stitches"), "text", "20")}${field("rows", t("rows"), "text", "28")}${field("width", t("width"), "text", "10")}${field("height", t("height"), "text", "10")}${unitSelect()}${textField("projectName", t("projectName"))}</div><button class="primary-button" type="submit">${t("calculate")} <span>↗</span></button><div id="result" class="result-slot"><p class="empty-result">${t("noResult")}</p></div></form>`; }
function countsForm() { return `<form id="counts-form" class="calculator-form"><div class="form-heading"><span class="step">01</span><div><p class="eyebrow">${t("density")}</p><h2>${t("density")}</h2></div></div><div class="form-grid">${field("stitchDensity", t("stitchDensity"), "text", "2")}${field("rowDensity", t("rowDensity"), "text", "2.8")}${field("targetWidth", t("targetWidth"), "text", "40")}${field("targetHeight", t("targetHeight"), "text", "60")}${unitSelect()}${textField("projectName", t("projectName"))}</div><div class="detail-switch" role="group" aria-label="Calculation detail"><button class="detail-button ${state.detailMode === "simple" ? "active" : ""}" data-detail-mode="simple" type="button" aria-pressed="${state.detailMode === "simple"}">${t("simpleMode")}</button><button class="detail-button ${state.detailMode === "advanced" ? "active" : ""}" data-detail-mode="advanced" type="button" aria-pressed="${state.detailMode === "advanced"}">${t("advancedMode")}</button></div><p class="detail-hint">${t("advancedHint")}</p><div class="advanced-settings" ${state.detailMode === "simple" ? "hidden" : ""}><fieldset><legend>${t("construction")}</legend><div class="segmented"><label><input type="radio" name="construction" value="flat" checked /><span>${t("flat")}</span></label><label><input type="radio" name="construction" value="round" /><span>${t("round")}</span></label></div></fieldset><div class="form-heading compact-heading"><span class="step">02</span><div><p class="eyebrow">${t("rules")}</p><h2>${t("rules")}</h2></div></div><div class="rules">${ruleBlock("stitch", t("stitchRule"), true)}${ruleBlock("row", t("rowRule"))}</div><p class="helper" id="round-helper" hidden>${t("edgeRound")}</p></div><button class="primary-button" type="submit">${t("calculate")} <span>↗</span></button><div id="result" class="result-slot"><p class="empty-result">${t("noResult")}</p></div></form>`; }

function read(id) { return parseLocalizedDecimal($(`#${id}`).value); }
function readText(id) { return $(`#${id}`)?.value.trim() || ""; }
function readCounts() { const simple = state.detailMode === "simple"; return { stitchDensity: read("stitchDensity"), rowDensity: read("rowDensity"), targetWidth: read("targetWidth"), targetHeight: read("targetHeight"), unit: $("#unit").value, construction: simple ? "flat" : document.querySelector("input[name=construction]:checked").value, stitchRule: { rounding: simple ? "nearest" : $("#stitchRounding").value, multiple: simple ? "1" : read("stitchMultiple"), offset: simple ? "0" : read("stitchOffset"), edgeStitches: simple ? "0" : read("edgeStitches") }, rowRule: { rounding: simple ? "nearest" : $("#rowRounding").value, multiple: simple ? "1" : read("rowMultiple"), offset: simple ? "0" : read("rowOffset") } }; }
function markErrors(errors) { for (const input of document.querySelectorAll("input, select")) input.removeAttribute("aria-invalid"); for (const item of errors) { const id = item.field.split(".").at(-1); const target = document.getElementById(id) || document.getElementById(item.field.replaceAll(".", "")); if (target) target.setAttribute("aria-invalid", "true"); } }
function bindForm() { const form = $(".calculator-form"); const unit = $("#unit"); unit.dataset.previous = unit.value; unit.addEventListener("change", () => convertVisibleValues(unit)); form.addEventListener("submit", (event) => { event.preventDefault(); const input = state.mode === "gauge" ? { projectName: readText("projectName"), stitches: read("stitches"), rows: read("rows"), width: read("width"), height: read("height"), unit: $("#unit").value } : { ...readCounts(), projectName: readText("projectName") }; const result = state.mode === "gauge" ? calculateGauge(input) : calculateCounts(input); markErrors(result.ok ? [] : result.errors); state.lastResult = result.ok ? result : null; state.lastInput = result.ok ? input : null; $("#result").innerHTML = result.ok ? resultView(result) : `<div class="error-message">${t("invalid")}<small>${result.errors.map(errorText).join(" · ")}</small></div>`; if (result.ok) saveHistory({ id: crypto.randomUUID(), timestamp: Date.now(), language: state.language, mode: state.mode, input, result }); });
  for (const radio of document.querySelectorAll("input[name=construction]")) radio.addEventListener("change", () => { $("#round-helper").hidden = radio.value !== "round" || !radio.checked; }); }
function convertVisibleValues(unit) { const from = unit.dataset.previous || "cm"; const to = unit.value; if (from === to) return; const locale = state.language === "ru" ? "ru-RU" : "en-US"; const fields = state.mode === "gauge" ? [["width", "length"], ["height", "length"]] : [["stitchDensity", "density"], ["rowDensity", "density"], ["targetWidth", "length"], ["targetHeight", "length"]]; fields.forEach(([id, kind]) => { const input = document.getElementById(id); if (input) input.value = convertUnitValue(input.value, from, to, kind, locale); }); unit.dataset.previous = to; }
function unitLabel(unit) { return unit === "in" ? t("inch") : t("cm"); }
function rationalNumber(exact) { return Number(exact.rational.numerator) / Number(exact.rational.denominator); }
function densityWarning(result) { return rationalNumber(result.stitchDensity) < 0.1 || rationalNumber(result.stitchDensity) > 100 || rationalNumber(result.rowDensity) < 0.1 || rationalNumber(result.rowDensity) > 100 ? `<p class="density-warning" role="status">${t("densityWarning")}</p>` : ""; }
function resultSummary(result) { const locale = state.language === "ru" ? "ru-RU" : "en-US"; if (result.kind === "gauge") return `<p class="result-summary">${t("summaryGauge")} ${formatExact(result.stitchDensity, locale)} ${t("stitchDensity")} · ${formatExact(result.rowDensity, locale)} ${t("rowDensity")}.</p>`; return `<p class="result-summary">${t("summaryCounts")} <strong>${result.stitches.final}</strong> ${t("stitches").toLowerCase()} · <strong>${result.rows.final}</strong> ${t("rows").toLowerCase()}. ${t("actual")} ${formatExact(result.stitches.actual, locale)} × ${formatExact(result.rows.actual, locale)} ${unitLabel(result.unit)}.</p>`; }
function resultView(result) { if (result.kind === "gauge") return `<div class="result"><div class="result-title"><p class="eyebrow">${t("result")}</p><h3>${t("gaugeResult")}</h3></div>${resultSummary(result)}<div class="result-highlight"><strong>${formatExact(result.stitchDensity, state.language === "ru" ? "ru-RU" : "en-US")}</strong><span>${t("stitchDensity")}</span><strong>${formatExact(result.rowDensity, state.language === "ru" ? "ru-RU" : "en-US")}</strong><span>${t("rowDensity")}</span></div>${densityWarning(result)}<button class="secondary-button" type="button" data-copy>${t("share")} <span>⌘</span></button></div>`; return `<div class="result"><div class="result-title"><p class="eyebrow">${t("result")}</p><h3>${t("countsResult")}</h3></div>${resultSummary(result)}${axisView(t("stitchRule"), result.stitches, true)}${axisView(t("rowRule"), result.rows, false)}<button class="secondary-button" type="button" data-copy>${t("share")} <span>⌘</span></button></div>`; }
function axisView(title, axis, edges) { return `<div class="axis"><div class="axis-top"><strong>${title}</strong><b>${axis.final}</b></div><div class="axis-details"><span>${t("raw")} <em>${formatExact(axis.raw, state.language === "ru" ? "ru-RU" : "en-US")}</em></span><span>${t("rounded")} <em>${axis.rule.rounding}</em></span><span>${t("actual")} <em>${formatExact(axis.actual, state.language === "ru" ? "ru-RU" : "en-US")}</em></span><span>${t("delta")} <em>${formatExact(axis.delta, state.language === "ru" ? "ru-RU" : "en-US")}</em></span></div>${edges ? `<small>${t("edge")}: ${axis.edgeStitches} · ${t("multiple")}: ${axis.rule.multiple} · ${t("offset")}: ${axis.rule.offset}</small>` : ""}</div>`; }

function copyCardText() { const result = state.lastResult; const input = state.lastInput; if (!result || !input) return $("#result").innerText; const locale = state.language === "ru" ? "ru-RU" : "en-US"; const title = input.projectName || (result.kind === "gauge" ? t("gaugeResult") : t("countsResult")); if (result.kind === "gauge") return `${title}\n${t("summaryGauge")}: ${formatExact(result.stitchDensity, locale)} ${t("stitchDensity")}, ${formatExact(result.rowDensity, locale)} ${t("rowDensity")}\n${t("unit")}: ${unitLabel(result.unit)}`; return `${title}\n${t("summaryCounts")}: ${result.stitches.final} ${t("stitches").toLowerCase()}, ${result.rows.final} ${t("rows").toLowerCase()}\n${t("actual")}: ${formatExact(result.stitches.actual, locale)} × ${formatExact(result.rows.actual, locale)} ${unitLabel(result.unit)}\n${t("rounded")}: ${result.stitches.rule.rounding} / ${result.rows.rule.rounding}`; }
async function copyResult() { try { await navigator.clipboard.writeText(copyCardText()); showToast(t("copied")); } catch { showToast(t("shareFailed")); } }
function showToast(message) { const toast = $("#toast"); toast.textContent = message; toast.classList.add("visible"); setTimeout(() => toast.classList.remove("visible"), 2200); }
function renderHistory() { $("#history-count").textContent = state.history.length; const list = $("#history-list"); if (!list) return; list.innerHTML = state.history.length ? state.history.map((entry) => `<button class="history-item" type="button" data-history-id="${entry.id}"><span><b>${entry.input.projectName || (entry.mode === "gauge" ? t("gaugeResult") : t("countsResult"))}</b><small>${entry.mode === "gauge" ? t("gaugeResult") : t("countsResult")} · ${formatDate(entry.timestamp, state.language === "ru" ? "ru-RU" : "en-US")} · ${entry.input.unit}</small></span><strong>${entry.mode === "gauge" ? formatExact(entry.result.stitchDensity, state.language === "ru" ? "ru-RU" : "en-US") : entry.result.stitches.final}</strong></button>`).join("") : `<p class="empty-history">${t("emptyHistory")}</p>`; }
function updateLanguage() { document.documentElement.lang = state.language; document.querySelectorAll("[data-i18n]").forEach((element) => { element.innerHTML = t(element.dataset.i18n); }); $("#language-button").textContent = state.language === "ru" ? "EN" : "RU"; }

document.addEventListener("click", (event) => { const mode = event.target.closest("[data-mode]"); if (mode) { state.mode = mode.dataset.mode; document.querySelectorAll(".mode-button").forEach((button) => { button.classList.toggle("active", button === mode); button.setAttribute("aria-selected", button === mode ? "true" : "false"); }); render(); } const detail = event.target.closest("[data-detail-mode]"); if (detail) { state.detailMode = detail.dataset.detailMode; document.querySelectorAll("[data-detail-mode]").forEach((button) => { const selected = button.dataset.detailMode === state.detailMode; button.classList.toggle("active", selected); button.setAttribute("aria-pressed", selected); }); const advanced = document.querySelector(".advanced-settings"); if (advanced) advanced.hidden = state.detailMode !== "advanced"; state.lastResult = null; state.lastInput = null; markErrors([]); const result = $("#result"); if (result) result.innerHTML = `<p class="empty-result">${t("noResult")}</p>`; } const copyButton = event.target.closest("[data-copy]"); if (copyButton) copyResult(); const historyItem = event.target.closest("[data-history-id]"); if (historyItem) { const entry = state.history.find((item) => item.id === historyItem.dataset.historyId); if (entry) { state.mode = entry.mode; state.detailMode = entry.result?.kind === "counts" && (entry.input?.stitchRule?.multiple !== "1" || entry.input?.construction === "round") ? "advanced" : "simple"; render(); restoreInput(entry.input); state.lastResult = entry.result; state.lastInput = entry.input; $("#result").innerHTML = resultView(entry.result); showToast(t("savedAt")); } } });

function restoreInput(input) {
  Object.entries(input).forEach(([key, value]) => {
    if (value && typeof value === "object") {
      const prefix = key === "stitchRule" ? "stitch" : "row";
      Object.entries(value).forEach(([nestedKey, nestedValue]) => { const target = document.getElementById(`${prefix}${nestedKey[0].toUpperCase()}${nestedKey.slice(1)}`); if (target) target.value = nestedValue; });
      return;
    }
    const target = document.getElementById(key);
    if (target) target.value = value;
    const radio = document.querySelector(`input[name="${key}"][value="${value}"]`);
    if (radio) radio.checked = true;
  });
}
$("#language-button").addEventListener("click", () => { state.language = state.language === "ru" ? "en" : "ru"; render(); });
$("#history-button").addEventListener("click", () => { const panel = $("#history-panel"); panel.hidden = !panel.hidden; if (!panel.hidden) panel.scrollIntoView({ behavior: "smooth", block: "start" }); });
$("#clear-history").addEventListener("click", () => { if (state.history.length && confirm(t("clearConfirm"))) { state.history = []; localStorage.removeItem(STORAGE_KEY); renderHistory(); } });
$("#export-history").addEventListener("click", () => { const blob = new Blob([JSON.stringify({ exportedAt: new Date().toISOString(), history: state.history }, null, 2)], { type: "application/json" }); const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = `marina-history-${new Date().toISOString().slice(0, 10)}.json`; link.click(); URL.revokeObjectURL(link.href); showToast(t("exported")); });
$("#print-result").addEventListener("click", () => window.print());
document.addEventListener("click", (event) => { if (event.target.closest(".secondary-button")) return; });
render();
if ("serviceWorker" in navigator) window.addEventListener("load", () => navigator.serviceWorker.register("./sw.js"));
